#/bin/bash
TYPE=svg

nombreArchivo=Arquitectura
dot $nombreArchivo.gv -T$TYPE -o Generados/$nombreArchivo.$TYPE
#inkscape -z -f Generados/$nombreArchivo.$TYPE --export-latex --export-pdf="Generados/$nombreArchivo.pdf"
#mv Generados/$nombreArchivo.pdf_tex Generados/$nombreArchivo.tex
#rm Generados/$nombreArchivo.pdf

TYPE=png
dot $nombreArchivo.gv -T$TYPE -o Generados/$nombreArchivo.$TYPE

Genera(){
  ## --use-part-section
  nombreArchivo=$1
  idioma=es
  generadoPor='/^Generated by \\href{/d'
  tipoDocumento=article
  tamPapel=letterpaper
  tamLetra=11pt
  opcionesDoc=$tamPapel,$tamLetra
  rst2xetex --template=latex2e/xelatex.tex --documentclass=$tipoDocumento --documentoptions=$opcionesDoc --use-latex-docinfo --use-latex-citations --figure-citations --section-subtitles --smart-quotes=yes -r 3 --section-numbering --compound-enumerators -l $idioma $nombreArchivo.rst $nombreArchivo.tex
  sed -i $generadoPor  $nombreArchivo.tex
  sed -i 's/{[ ]*/{/g' $nombreArchivo.tex
  sed -i 's/[ ]*}/}/g' $nombreArchivo.tex
  #sed -i 's/\\end{quote}/\\end{quotation}/g' $nombreArchivo.tex

  latexmk -latexoption="-synctex=1 -interaction=batchmode -shell-escape" -xelatex $nombreArchivo.tex
}

nombreArchivo=XMPP_Federado
Genera $nombreArchivo

nombreArchivo=borrador
Genera $nombreArchivo

nombreArchivo=draft_en
Genera $nombreArchivo

nombreArchivo=cheatsheet
Genera $nombreArchivo
