#/bin/bash

Genera(){
  ## --use-part-section
  nombreArchivo=$1
  generadoPor='/^Generated by \\href{/d'
  rst2xetex --template=latex2e/xelatex.tex --documentclass=article --documentoptions=letterpaper,11pt --use-latex-docinfo --section-subtitles --smart-quotes=yes -g -l es $nombreArchivo.rst $nombreArchivo.tex
  sed -i $generadoPor  $nombreArchivo.tex
  #sed -i 's/\\begin{quote}/\\begin{quotation}/g' $nombreArchivo.tex
  #sed -i 's/\\end{quote}/\\end{quotation}/g' $nombreArchivo.tex

  latexmk -xelatex $nombreArchivo.tex
}

nombreArchivo=XMPP_Federado
Genera $nombreArchivo

nombreArchivo=borrador
Genera $nombreArchivo

nombreArchivo=draft_en
Genera $nombreArchivo